---
title: Chris Muccioli
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
keywords: test, test, testing
author: Tomasz Werner
email: your-email@domain.com
description: 'Write an awesome description for your new site here.'
markdown: kramdown
theme: minima
defaults:
  -
    scope:
      path: ""
      type: "posts"
    roles: ""
    credits: ""
    video-source: ""
    thumbnail-source: ""
